# Generated by Django 4.1.6 on 2023-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("iata", models.CharField(max_length=3, unique=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inactive_reason",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "airport",
            },
        ),
    ]
